# Use official Node image
FROM node:16

# Set working directory inside container
WORKDIR /app

# Copy files
COPY package*.json ./
RUN npm install
COPY . .

# Expose port and start app
EXPOSE 3000
CMD ["npm", "start"]
